<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Andreja.Api.Contracts\Andreja.Api.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Andreja.Platform.Contracts\Andreja.Platform.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Andreja.Modules\Andreja.Modules.csproj" />
    <ProjectReference Include="..\..\src\Adapters\Andreja.Adapters\Andreja.Adapters.csproj" />
  </ItemGroup>

</Project>