<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Andreja.Api.Contracts\Andreja.Api.Contracts.csproj" />
    <ProjectReference Include="..\Andreja.Platform.Contracts\Andreja.Platform.Contracts.csproj" />
    <ProjectReference Include="..\Modules\Andreja.Modules\Andreja.Modules.csproj" />
    <ProjectReference Include="..\Adapters\Andreja.Adapters\Andreja.Adapters.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <NoDefaultLaunchSettingsFile>True</NoDefaultLaunchSettingsFile>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
